### ISSUE TITLE
vryjs.exe detected as trojan and malware

### ISSUE THREAD

**Issue by EggPiss** [tanishqmanuja/valorant-rank-yoinker-js#1]
virustotal detected vryjs.exe as trojan and malware but the original val rank yoinker is not detected as anything, any clues why?

**Comment by tanishqmanuja** [comment]
No idea about how they flag exe files, but i will look into it for sure.
But the best part about open source is that you can look into the code yourself to see that there's nothing suspicious, so that's a false positive virus detection.

**Comment by tanishqmanuja** [comment]
Looks like it's because of Go runtime 
https://go.dev/doc/faq#virus

**Comment by EggPiss** [comment]
ah i see thanks
